name: adhesivegirl

on:
  push:
    paths:
      - 'adhesivegirl/**'
        #- '.github/workflows/adhesivegirl.yml' #testing

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: set default scheme
        run: |
          cd adhesivegirl/Builds/MacOSX
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: build
        env:
          scheme: ${{ 'default' }}
        run: |
          cd adhesivegirl/Builds/MacOSX
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: adhesivegirl-mac
          path: |
            adhesivegirl/Builds/MacOSX/build/Release
  win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: add msbuild to path
      uses: microsoft/setup-msbuild@v1.1
    - name: build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release adhesivegirl/Builds/VisualStudio2019/adhesivegirl.sln
    - name: save artifacts
      uses: actions/upload-artifact@v3
      with:
        name: adhesivegirl-win
        path: |
          adhesivegirl\Builds\VisualStudio2019\x64\Release
  release:
    runs-on: ubuntu-latest
    needs: [mac, win]
    steps:
      - uses: actions/download-artifact@v3
      - name: ziptie
        run: |
          mkdir void
          zip -r adhesivegirl-mac-vst.zip adhesivegirl-mac/adhesivegirl.vst3/
          zip -r adhesivegirl-mac.zip adhesivegirl-mac/
          zip -r adhesivegirl-win.zip adhesivegirl-win/
          cp adhesivegirl-mac-vst.zip adhesivegirl-mac.zip adhesivegirl-win/VST3/adhesivegirl.vst3 adhesivegirl-win.zip void/
      - name: release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: void/*
          tag: adhesivegirl
          overwrite: false
          file_glob: true
          body: "may you be happy"
