name: release-test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: hi
      shell: bash
      run: |
        mkdir test
        echo "trans them!" > test/file1
        echo "trans them all!" > test/file2
        
    - uses: edgarrc/action-7z@v1
      with:
        args: 7z a -tzip test.zip -r test
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "lmao"
        prerelease: true
        title: "hot stuff"
        files: |
          test.zip
